### ISSUE TITLE
Crash on launch on Forge dedicated server due to loading PoseStack

### ISSUE THREAD

**Issue by PaintNinja** [GroovyMC/CommonGroovyLibrary#1]
Crash report: https://mclo.gs/INQ0jLu

To reproduce:
1. Clone this repo
2. Comment out the WIP `BufferEncodable` test
3. Import into IDE
4. Run genIntellijRuns
5. Start "Forge Server" run configuration

**Comment by lukebemish** [comment]
Huh. We don't seem to reference PoseStack anywhere that I can find

**Comment by lukebemish** [comment]
If you comment out the method in Minecraft Extensions does the issue still occur?

**Comment by lukebemish** [comment]
Wait. Could it be one of the math extensions causing loading of PoseStack somehow?

**Comment by PaintNinja** [comment]
> If you comment out the method in Minecraft Extensions does the issue still occur?

Yes, still occurs without `io.github.groovymc.cgl.extension.client.MinecraftExtensions`

**Comment by lukebemish** [comment]
Alright then. Weird. Does it happen in production?

**Comment by PaintNinja** [comment]
Set up a Forge 43.1.27 production server and installed GML 1.2.1 (which has CGL 0.1.0 JIJ'ed) and it works - doesn't crash in production.
Debug log from production: https://mclo.gs/cZLUvho

**Comment by lukebemish** [comment]
So fun fact... This is due to ArithmeticExtension, but only on forge. Because ArithmeticExtension loads Transformation. That's normally fine, but forge's extension interface it shoves on transformation, `IForgeTransformation`, loads PoseStack

**Comment by lukebemish** [comment]
Going to close this since I believe it's fixed now
